export enum DiaDaSemana { //ENUM É SOMENTE LEITURA, POR PADRÃO E O PRIMEIRO ITEM É SEMPRE 0 (NO CASO DOMINGO)
    DOMINGO = 0,
    SEGUNDA = 1,
    TERCA=2,
    QUARTA =3,
    QUINTA=4,
    SEXTA =5,
    SABADO =6
}



 //PARA NAO CORRER O RISCO DE SE PERDER NOS NUMEROS, VAMOS JÁ ATRIBUIR OS VALORES PRAS VAR, MAS NAO PRECISA