export enum DiaDaSemana { //ENUM É SOMENTE LEITURA, POR PADRÃO E O PRIMEIRO ITEM É SEMPRE 0 (NO CASO DOMINGO)
    DOMINGO,
    SEGUNDA,
    TERCA,
    QUARTA,
    QUINTA,
    SEXTA,
    SABADO
}



 //PARA NAO CORRER O RISCO DE SE PERDER NOS NUMEROS, VAMOS JÁ ATRIBUIR OS VALORES PRAS VAR, MAS NAO PRECISA